name: CI workflow with java


on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
        java-version: '17'
        distribution: 'temurin'
        

  # Runs a set of commands using the runners shell
      - name: build with maven
        run: mvn --batch-mode --update-snapshot package
          echo Add other actions to build,
          echo test, and deploy your project.
